[package]
name = "chamkho"
version = "0.3.0" 
authors = ["Vee Satayamas <vsatayamas@gmail.com>"]
description = "Lao/Thai word segmentation/breaking library and command line"
documentation = "https://github.com/veer66/chamkho/blob/master/README.md"
homepage = "https://github.com/veer66/chamkho"
repository = "https://github.com/veer66/chamkho"
readme = "README.md"
keywords = ["text", "nlp", "lao", "thai", "library"]
license = "LGPL-3.0"

[[bin]]
name = "wordcut"
path = "src/cli.rs"

[dependencies]
clap = { version = "1", features = ["yaml"] }
wordcut-engine = "0.1.1"